### ISSUE TITLE
Improve documentation of the `GitFileHandler`

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/py-capellambse#101]
> The attributes (apart from username and password) can have a docstring.

Some are already documented on the `FileHandler` ABC, we should add a link to it and explicitly mention which ones we support here.

> The `open` method doesn't have a docstring yet

It uses the same docstring as the base class.

The Numpy style guide for docstrings doesn't explicitly say anything about this case AFAICT. The Google style however says to [insert a docstring à la """See base class"""](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods). I'll raise this in our next regular meeting, where we can discuss it properly with the entire team.

> and `write_transaction` is referencing a private class' docstring (`_GitTransaction`).

It isn't *referencing*, but rather *copying* it: https://github.com/DSD-DBS/py-capellambse/blob/0b559bede262d61d2e89618c7d1b948bd17146ef/capellambse/loader/filehandler/gitfilehandler.py#L567

Or was your point that we shouldn't do this? (In which case, I'm curious as to why?)

_Originally posted by @ewuerger in https://github.com/DSD-DBS/py-capellambse/pull/99#pullrequestreview-1010237033_

**Comment by ewuerger** [comment]
I think I was not hovering over the open method and therefore didn't see that there was an infered docstring from its parent-class base-class. I appreciate that you researched and shared what to do in this case.

**Comment by Wuestengecko** [comment]
> we should add a link to it and explicitly mention which ones we support

That's not done yet, as far as I know.

> I'll raise this in our next regular meeting, where we can discuss it properly with the entire team.

The discussion isn't over yet :)

Let's keep this open until these points are done.
