### ISSUE TITLE
[BUG] Boolean attributes create not working when 'value' field is set to False

### ISSUE THREAD

**Issue by jeremy-jimmy** [DSD-DBS/py-capellambse#108]
As shown below, when I try to create a boolean attribute to a requirement it's working only when I don't precise the option "value" when I intend to set the attribute to False value, and it's working perfectly when I precise True as a value.

Is it an intentionnal behavior or is it a wrong handling of the create function ?

Thanks in advance.

`
import capellambse
model = capellambse.MelodyModel(PATH_CAPELLA, jupyter_untrusted=True)

# Getting my custom requirement_type
REQ_TYPE = model.pa.requirement_types_folders[0].requirement_types[0]

# Getting where I want to write my requirement
FOLDER = model.pa.requirement_modules[0].folders[0]

# Creation of test_req
TEST = FOLDER .requirements.create(name="TEST_REQ_1", long_name="Exigences test #1", type=REQ_TYPE)

# Boolean attribute creation with value set to True: OK
TEST.attributes.create("bool", name="attr_1", value=True, definition=ATTR_TYPES["REQUIRED"])

# Boolean attribute creation with value set to False : KO ==> AttributeError: 'NoneType' object has no attribute 'rsplit'
TEST.attributes.create("bool", name="attr_2", value=False, definition=ATTR_TYPES["REQUIRED"])

# Boolean attribute creation without value precised : OK, attribute set to False by default
TEST.attributes.create("bool", name="attr_2",  definition=ATTR_TYPES["REQUIRED"])
`

**Comment by vik378** [comment]
Can reproduce that too and it seems to be a chain of tiny issues

![image](https://user-images.githubusercontent.com/8280844/180307315-7e15af07-c816-4fd3-ba70-14c81c7ab38e.png)

I added a test case that catches that issue

**Comment by ewuerger** [comment]
With this I go to sleep now:
![](https://i.ibb.co/3WBjdJg/datetime-bug.png)
