### ISSUE TITLE
Bad handling of XML special characters in HTML fields

### ISSUE THREAD

**Issue by jeremy-jimmy** [DSD-DBS/py-capellambse#113]
Hi,

I'm facing a bug which seems to be due to a bad handling of the utf-8 encoding of strings in the module capellambse\loader\xmltools.py according to my investigations described below :

`
req = folder.requirements.create(name=data["ID"])
`

**I did some basic debug printing in the module and here what I observe :**

`

        stringified = str(value)
        
        print("INTERNAL_DEBUG, stringified :", stringified)
        print("INTERNAL_DEBUG, value :", value)
        print("INTERNAL_DEBUG, comp :", stringified==value)
        print("INTERNAL_DEBUG, returntype :", self.returntype(stringified))

        try:
            roundtripped = self.returntype(stringified)
        except (TypeError, ValueError) as err:
            raise TypeError(f"Value is not round-trip safe: {value}") from err

        if roundtripped != value:
            raise TypeError(f"Value is not round-trip safe: {value}")
`

**And here is my output :** 

```
INTERNAL_DEBUG, stringified : Le tableau d'alimentation 
INTERNAL_DEBUG, value : Le tableau d'alimentation
INTERNAL_DEBUG, comp : True
INTERNAL_DEBUG, returntype : Le tableau d&#x27;alimentation
```

**Comment by Wuestengecko** [comment]
Hi! Thanks for the report. I was able to reproduce on current `master` (89ca58b49e2e160ddb228532531c45fbf3971f8e) with:

    folder.requirements.create(text="Le tableau d'alimentation")

... but not with `(name=...)`. Can you double-check and try to repro with the latest `master` version?

Anyway, this seems to be an issue with how we handle (and check) the input to HTML attributes - the `Requirement.text` attribute accepts HTML, not just a plain string. If something is passed in that is not valid HTML, we currently delegate to `markupsafe` to make it valid, but that results in changes to the passed-in string and triggers the "Value is not round-trip safe" exception.

**Comment by Wuestengecko** [comment]
I've made some changes to the way how we handle HTML attributes on the `113-bad-handling-of-xml-special-characters-in-html-fields` branch. This now shows the following output:

```python
>>> folder = model.search("Requirements:Folder")[0]
>>> req = folder.requirements.create(text="Le tableau d'alimentation")  # This used to crash
>>> req.text
Markup('Le tableau d&#x27;alimentation')
>>> req.text.unescape()
"Le tableau d'alimentation"
```

Would that work for you? And can you perhaps try it out with your production code as well, before we merge it?

You can install the development branch it by running:

    pip install https://github.com/DSD-DBS/py-capellambse.git@113-bad-handling-of-xml-special-characters-in-html-fields

**Comment by jeremy-jimmy** [comment]
Hi, thanks again for such reactivity. I will test this asap, probably tomorrow if my current task go as expected. I will let you know ;)

**Comment by jeremy-jimmy** [comment]
Hi again, I just tested the fix for my bug on my production code and it's working perfectly. 

And by the way, indeed you were right, it was not the "name" attributes causing troubles but "text".

Thanks for the fix and have a nice day, 

Do you know when version 0.4.13 will be release ?

**Comment by Wuestengecko** [comment]
Thanks for the feedback!

Seeing how we've gone quite a long time since the last release already, we're going to make a new one as soon as the fix lands. Expect it sometime today or tomorrow.
