### ISSUE TITLE
Solve owner/parent attribute for GenericElements

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/py-capellambse#18]
I start with an example:

LogicalFunctions.owner attribute currently links to the LogicalComponent where this function is allocated to(it is in component.allocated_functions). This behaviour was introduced when we wanted to access the owners of Functions displayed in diagrams. But in the explorer the owner should be either of type LogicalFunction or LogicalFunctionPkg.

In capella's semantic browser it says:
![image](https://user-images.githubusercontent.com/50786483/141102917-49f5fac9-4687-4739-b09d-4647ef8ba8ae.png)

Here it is called parent. We should be consistent with the naming of attributes on ModelElements to not confuse the user and most importantly ourselves.

**Comment by vik378** [comment]
I think it is fine to keep "owner" as a shortcut to component that the function is allocated to. But what we missed out is a structural "parent" and that we should have maybe even at GenericElement level

**Comment by Wuestengecko** [comment]
This looks very much like a legitimate issue to me, I'm gonna go ahead and remove the "invalid" tag again. (That tag is for bugs that aren't our fault (e.g. due to buggy dependencies), "bugs" that are actually features/intended behavior, etc.)
