### ISSUE TITLE
More useful `__repr__`s for reqif

### ISSUE THREAD

**Issue by ewuerger** [DSD-DBS/py-capellambse#219]
While working on synthesis of commit statements I stumpled upon the representation of `reqif.AttributeValue`s. For example:
```
>>> f"{attr!r}"
EnumerationValueAttribute 37a8a7bb-2f01-466f-ae42-09b7fcedf812
```
is missing a key information (its `.value` or `.values`). I propose that this `__repr__` is extended by this kind of information. `reqif.EnumValue`s for example incorporate its (only) information already (because its their long_name):

```
>>> f"{ev!r}"
EnumValue applicable
```

**Comment by Wuestengecko** [comment]
Please provide a minimal, reproducible example. I tried the following, and it looks very different from what you describe:

```
============================== Model exploration ===============================
`model` is '5_0' from tests/data/melodymodel/5_0/Melody Model Test.aird

>>> attr = model.search("EnumerationValueAttribute")[0]
>>> print(repr(attr))
<EnumerationValueAttribute 'MultiEnum' (148bdf2f-6dc2-4a83-833b-596886ce5b07)>
```

**Comment by Wuestengecko** [comment]
I supposed we can close this now. The `repr()` in reqif has evolved even more, and if you have further ideas for improvement, just open a new issue.
