### ISSUE TITLE
Git file handler crashes on local repos without a remote

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/py-capellambse#224]
The git file handler always tries to contact some remote to look for updates, even when it was provided a local checkout. If said checkout does not have a remote (e.g. because it wasn't cloned from somewhere else), this leads to the following crash:

```
$ cd "$(mktemp -d)"
$ git init
$ python -c 'import os, capellambse; capellambse.get_filehandler("git+" + os.getcwd())'
fatal: couldn't find remote ref HEAD
Exit status: 128
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[…]/capellambse/capellambse/filehandler/__init__.py", line 85, in get_filehandler
    return handler(path, **kwargs)
  File "[…]/capellambse/capellambse/filehandler/git.py", line 535, in __init__
    self.__init_cache_dir()
  File "[…]/capellambse/capellambse/filehandler/git.py", line 669, in __init_cache_dir
    self.__init_cache_dir_remote()
  File "[…]/capellambse/capellambse/filehandler/git.py", line 714, in __init_cache_dir_remote
    self._git("fetch", self.path, *shallow_opts)
  File "[…]/capellambse/capellambse/filehandler/git.py", line 834, in _git
    proc = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'fetch', '/tmp/tmp.ZNEfQoK8QO', '--depth=1', '+HEAD']' returned non-zero exit status 128.
```

GitFileHandler should not attempt to contact a remote at all if the provided `path` was not a remote repository.

**Comment by malnemark** [comment]
I think I have a related issue here, however it also occurred similarly with a local path, without a git repository. 

This is the output with a local file ("Kaffeemaschine"), however same error occured when trying to load a local file inside a git-tracked folder:


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 path_to_model = r"C:\Capella\Kaffeemaschine\Kaffeemaschine.aird"
----> 2 model = capellambse.MelodyModel(path_to_model, jupyter_untrusted=True)

File ~\AppData\Local\Python\Python39\site-packages\capellambse\model\__init__.py:235, in MelodyModel.__init__(self, path, diagram_cache, diagram_cache_subdir, jupyter_untrusted, **kwargs)
    232 capellambse.load_model_extensions()
    234 self._constructed = False
--> 235 self._loader = loader.MelodyLoader(path, **kwargs)
    236 self.jupyter_untrusted = jupyter_untrusted
    238 try:

File ~\AppData\Local\Python\Python39\site-packages\capellambse\loader\core.py:388, in MelodyLoader.__init__(self, path, entrypoint, resources, **kwargs)
    386     handler = path
    387 else:
--> 388     handler = filehandler.get_filehandler(path, **kwargs)
    389 self.resources = ResourceLocationManager({"\0": handler})
    390 for resname, reshdl in (resources or {}).items():

File ~\AppData\Local\Python\Python39\site-packages\capellambse\filehandler\__init__.py:84, in get_filehandler(path, **kwargs)
     82 def get_filehandler(path: str | os.PathLike, **kwargs: t.Any) -> FileHandler:
     83     handler_name, path = split_protocol(path)
---> 84     handler = load_entrypoint(handler_name)
     85     return handler(path, **kwargs)

File ~\AppData\Local\Python\Python39\site-packages\capellambse\filehandler\__init__.py:69, in load_entrypoint(handler_name)
     67 except StopIteration:
     68     raise ValueError(f"Unknown file handler {handler_name}") from None
---> 69 return ep.load()

File C:\Python3.9.10\lib\importlib\metadata.py:77, in EntryPoint.load(self)
     72 """Load the entry point from its definition. If only a module
     73 is indicated by the value, return that module. Otherwise,
     74 return the named object.
     75 """
     76 match = self.pattern.match(self.value)
---> 77 module = import_module(match.group('module'))
     78 attrs = filter(None, (match.group('attr') or '').split('.'))
     79 return functools.reduce(getattr, attrs, module)

File C:\Python3.9.10\lib\importlib\__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:981, in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'capellambse.loader.filehandler.localfilehandler'; 'capellambse.loader.filehandler' is not a package

**Comment by Wuestengecko** [comment]
@malnemark That's a different issue. How did you install capellambse? It should be solved by simply doing `pip install -U capellambse` in the simplest case, but there might be stale metadata laying around somewhere, which confuses the import logic. (You might be able to fix that by doing `pip uninstall capellambse` first.)
