### ISSUE TITLE
Optimizing export_diagrams method

### ISSUE THREAD

**Issue by jamilraichouni** [DSD-DBS/py-capellambse#230]
> I see big potential for optimizing this method. Right now it:
>
> 1. Lets Capella generate the images
> 2. Copies the images somewhere else
> 3. Goes back and fixes the file names of the copied images
> 4. Goes back once more and applies some post processing to the copied images
>
> If anything during or after step 2 fails, we end up with bad images in the target directory: If it fails before (3) is done, there will be badly named files, if it fails during (4) some files will have bad content.
> 
> I'd suggest to refactor it to apply all the post-processing and renaming in flight (during copying). This reduces the number of OS file operations, and it allows us to leverage the `FileHandler` infrastructure, more specifically its `write_transaction()`. For local file systems, it even has benefits as well, like atomicity (at least emulated) and therefore better consistency in the case of errors.
 
_Originally posted by @Wuestengecko in https://github.com/DSD-DBS/py-capellambse/pull/186#discussion_r1021865840_

**Comment by Wuestengecko** [comment]
Fixed in 8d16678f337342f5ec1eea7bfcac895b884a6f45.
