### ISSUE TITLE
realizing_ / realized_ attributes

### ISSUE THREAD

**Issue by kairibu** [DSD-DBS/py-capellambse#233]
Hi all, it seems the library doesnt yet provide access to the attributes "realizing" and "realized", which links different artefacts between the OA, SA, LA, PA layers. 
I only found it implemented for Functions (LF,SF) (edit: and Components on LA and PA). But not for Component Exchanges and Functional Exchanges.

Maybe if you provide an example how to add to one artefact type / one layer, I could contribute to add attributes for further types.

**Comment by malnemark** [comment]
Hi, I wanted to bump up this issue again.

**Comment by kairibu** [comment]
Hi Wuestengecko, thanks for looking into this. Have you been able to include realized/realizing attributes also for Component Exchanges? I pulled latest version but wasn't able to find it.

And one thing I noticed with the update: Now allocating_physical_link and allocating_physical_path appear on component exchanges on all Architecture layers, even though I think it should only appear on PA.

**Comment by Wuestengecko** [comment]
> Have you been able to include realized/realizing attributes also for Component Exchanges?

Ah, I must have missed those, damn it.

> Now allocating_physical_link and allocating_physical_path appear on component exchanges on all Architecture layers, even though I think it should only appear on PA.

This is actually how it is in the metamodel, and it's also been this way before. (I agree it doesn't make sense outside of PA, but there's only one "ComponentExchange" class which is reused across all layers, so it must have all possible attributes.)
