### ISSUE TITLE
Rename "diagram cache" to "diagram image cache"

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/py-capellambse#247]
To make it less ambiguous what the feature is about, we should explicitly mention that it's about the graphical representations of the diagrams, i.e. images.

This includes the main entry point method `update_diagram_cache`, which constitutes a breaking API change. Therefore there will be a deprecation period.

**Comment by hi-malik** [comment]
Hi @Wuestengecko can you please assign this issue to me.

**Comment by Wuestengecko** [comment]
Hey! We haven't heard from you in a while. Are you still working on this? If not, I'd unassign this so that someone else may take over.

**Comment by Wuestengecko** [comment]
Unassigning due to lack of response.

**Comment by Wuestengecko** [comment]
This will not be happening after all, see https://github.com/DSD-DBS/py-capellambse/pull/353#issuecomment-1845414481
