### ISSUE TITLE
Introduce basic native support for Filtering extension

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/py-capellambse#252]
Capella has a Filtering extension that provides basic means for model-based variability management. Using this thing you may define on your 150% architecture model what model elements correspond to a "feature" (`FilteringCriterion`), group those features into configurations (`FilteringResult`), have dynamic filtering of views (to preview 100% model on a diagram) and export resulting 100% architecture in a stand-alone model.

You may find more details about the extension here: 
- Introduction: https://github.com/eclipse/capella-filtering/blob/master/plugins/org.polarsys.capella.filtering.doc/html/User%20Manual/Introduction.mediawiki 
- Meta-model: https://github.com/eclipse/capella-filtering/blob/master/plugins/org.polarsys.capella.filtering.doc/html/User%20Manual/Appendix.mediawiki
- Functionality deep-dive: https://github.com/eclipse/capella-filtering/blob/master/plugins/org.polarsys.capella.filtering.doc/html/User%20Manual/Functionalities.mediawiki

Our basic need is to be able to identify if a model element is associated to a FilteringCriterion and list all FilteringCriterions that a model has. The short term goal is to provide enough API support for this so that we could export an HTML page with description of what components / functions / interfaces are available always and what are only available when a specific feature is included (FilteringCriterion is selected).

**Comment by Wuestengecko** [comment]
The model side of the extension seems to be primarily using the basic building blocks that Capella models also use. In that case, implementing support for it should be relatively simple.

The most immediately interesting part seems to be this extension element, which may appear nested below any model object (as far as I understood):

```xml
<ownedFunctions xsi:type="org.polarsys.capella.core.data.oa:OperationalActivity"
    id="d307e5fc-b586-408b-ae25-537522c1b72d" name="eat monster meat">
  <ownedExtensions xsi:type="filtering:AssociatedFilteringCriterionSet"
      id="525f993d-8132-422d-9c7d-c51e8944a82f" filteringCriteria="#43999f80-e919-4cfe-9590-79576a50cb5b #acc64274-ac37-4383-a5b9-abf1ded311b6"/>
</ownedFunctions>
```

The `filteringCriteria` attribute there refers to the individual "filtering criteria" defined in the filtering model, which is nested directly below the `SystemEngineering` object (next to the architecture layers), as indicated by the meta-model.
