### ISSUE TITLE
getReferencingElements

### ISSUE THREAD

**Issue by MS34449** [DSD-DBS/py-capellambse#256]
To prevent dangling references caused e.g. by deletion of model elements they used to point to, the API should offer also the possibility to collect all elements referencing a particular target element.

This opens some further, related possibilities. E.g. when a synchronisation is being carried out via [the rm-bridge](https://github.com/DSD-DBS/capella-rm-bridge), one could make the automatic deletions that happen during modification of the target model also explicitly visible in the changeset which is applied by the rm-bridge.

The implementation of this functionality depends on the internal representation and persistence of the model (e.g. a  graph DB) and may of course be changed over time.

**Comment by Wuestengecko** [comment]
I'm marking this as "model breaking", because this function is a prerequisite for cleaning up dangling references; not cleaning them up breaks a model.
