### ISSUE TITLE
Option to disable fallback renderer if a diagram cache is in use

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/py-capellambse#287]
We occasionally see issues where diagrams aren't properly put into or pulled from the pre-rendered diagram image cache. In some instances, this causes the (internally rendered) diagrams to look just off enough to cause hard-to-spot issues down the line, especially if people aren't paying close attention because they think everything went fine.

We should add more tools to better deal with this type of situation. My first proposal would be to add an option that entirely disables the fallback renderer if a diagram cache was configured for a model. This could (should?) be made the default, so that people who want the fallback have to explicitly opt into it.

My proposal would be to add an environment variable like `CAPELLAMBSE_FALLBACK_RENDER_AIRD`, which, if absent (the default), will disable the fallback renderer. Alternatively, we could also add a model argument, which would make it configurable on a per-model basis.

The variable should not have any effect if no `diagram_cache` argument was given, i.e. if there is no cache to pull images from, we will always render them internally.

Care needs to be taken so that this change does not negatively impact diagrams that are always internally rendered, such as ones made with [capellambse-context-diagrams](https://github.com/DSD-DBS/capellambse-context-diagrams).

**Comment by vik378** [comment]
the fallback renderer is still a thing in a few usecases, I think we shouldn't make it difficult to use. I'd rather see this as a per-model option and also only disable it given the cache (enabled by default) so that we dont end up with no means to render

**Comment by Wuestengecko** [comment]
I don't want to make it difficult to use either, I just want it to be disabled by default for AIRD diagrams :)

And yes, if there's no cache specified at all then we will always need to use the internal engine, otherwise we wouldn't be able to display anything.

So my understanding of your point is:

- If there's a cache, disable the renderer _unless_ an additional argument was passed during model loading
- If there's no cache, keep the renderer enabled

That sounds good to me.
