### ISSUE TITLE
Problem with PhysicalComponents

### ISSUE THREAD

**Issue by core-engineering** [DSD-DBS/py-capellambse#295]
Hi,

First, I would like to thanks all the team for such a good tool !

Secondly, I would like to share one problem I have with PhysicalComponents.

When I try to access to nodes of a diagram I could do the following :

![01](https://github.com/DSD-DBS/py-capellambse/assets/24791015/07dd7ed4-14df-469a-8ce3-15374f4ce766)

![02](https://github.com/DSD-DBS/py-capellambse/assets/24791015/b3677a5b-2988-43ec-a66e-3d31538dc7ff)

![03](https://github.com/DSD-DBS/py-capellambse/assets/24791015/db7fa7a2-be88-488c-b96a-6419b2ccaf3c)

But when I try to do quite the same thing with PhysicalComponents something doesn't work the way I expect.

I can do the following :

![04](https://github.com/DSD-DBS/py-capellambse/assets/24791015/1d006431-d2df-4234-afa1-5e380b2e21f0)

![05](https://github.com/DSD-DBS/py-capellambse/assets/24791015/50b38d88-3afc-4e7c-9570-030895d0e615)

![07](https://github.com/DSD-DBS/py-capellambse/assets/24791015/3ba9378b-372e-4bbb-a167-fcc0db93325d)

But the next code seems not working and I need to stop it manually : 

![06](https://github.com/DSD-DBS/py-capellambse/assets/24791015/a4d1871d-75a7-4aa6-8c63-72cf82d9d0f4)

Is this behaviour normal ? What would be the explanation for that ?

Thanks and regards

**Comment by Wuestengecko** [comment]
I can't seem to reproduce this with any of our models, displaying objects consistently takes less than a second for me. Could you post the full stack trace of the KeyboardInterrupt from your last screenshot? That should give us a hint at what it was doing that took so long.

**Comment by core-engineering** [comment]
Following your comment, I have tried to look at the full stack trace of the KeyboardInterrupt and unfortunetly it is not reproducible. I have tried also to not interrupt the process. It took 1m38s for the instruction ```model.pa.all_components[0]```. So It works but very slowly ! I's true that I have 300 PhysicalComponents in my model. Do you think it is only due to the model size ?
