### ISSUE TITLE
Git model loader should not depend on LFS

### ISSUE THREAD

**Issue by amolenaar** [DSD-DBS/py-capellambse#32]
We can not expect every user to put his/her models in Git LFS (Large File Storage).

Martin wrote](https://github.com/DSD-DBS/py-capellambse/pull/22#discussion_r747661637):

>I'd consider the hard requirement on Git LFS a bug. Although it has become quite common, we still can't just require everyone to install LFS even if they don't use it.
>After a brief look at the affected code, it should be fairly straight-forward to catch the produced error and pretend that git lfs ls-files had simply listed nothing. Getting test coverage on both cases in a single test run might become annoying though :)

Suggested solutions:
* Create separate loaders for "normal" git and git lfs
* Try with git lfs and fall back to normal git

**Comment by Wuestengecko** [comment]
Fixed since 631a4f87582260774f9ed67d17b1c04a92624587, which implements the second suggested solution ("Try with git lfs and fall back to normal git").
