### ISSUE TITLE
Improve requirement object appearance in display context

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/py-capellambse#38]
By default a requirement object is described as GenericElement, however since it is closer to ReqIF element it needs to be described differently - the following attributes should be visible:

- [ ] RegIF long name
- [ ] ReqIF identifier
- [ ] ReqIf text
- [ ] ReqIF attributes (if any)
- [ ] links (if any)

**Comment by ewuerger** [comment]
ReqIF related ModelElements have the bespoken attributes displayed in jupyter:
![image](https://user-images.githubusercontent.com/50786483/151194512-87225035-f882-454a-9897-baac4bbd013c.png)
