### ISSUE TITLE
pc.components versus py.deployed_components

### ISSUE THREAD

**Issue by kairibu** [DSD-DBS/py-capellambse#457]
When a node Physical Component deploys behaviour components, the deployed components appear under 

physicalcomponent.components

and

physicalcomponent.deployed_components

As user I would like to be able to filter either deployed or owned components.

**Comment by Wuestengecko** [comment]
Hi! There's also `PhysicalComponent.owned_components`. `components` here is just a convenience alias for `deployed_components + `owned_components`. Does this do what you're looking for?

**Comment by kairibu** [comment]
yes, thx
