### ISSUE TITLE
Handle unavailability of diagram in diagram_cache

### ISSUE THREAD

**Issue by jamilraichouni** [DSD-DBS/py-capellambse#46]
When `MelodyModel` is being loaded with a filled `diagram_cache` param, we try to request diagrams from the so called Capella diagram service.

When such a request is not returning a diagram, the algorithm shall fallback to the internal diagram engine.

That kind of behaviour will also cover cases where we access synthentic context diagrams.

**Comment by Wuestengecko** [comment]
> When such a request is not returning a diagram, the algorithm shall fallback to the internal diagram engine.

It is already (supposed to be) doing exactly that:

https://github.com/DSD-DBS/py-capellambse/blob/248642ed0bb405f30d7cb7aaf6db1e4d7617e949/capellambse/model/diagram.py#L145-L149

Is this not working properly? If so, what's the exact error message / stack trace?

**Comment by vik378** [comment]
Somehow it isnt when we have cache injected, the failure happens when `.context_diagram` attempts pulling a non-existing diagram from the cache. But it doesnt seem to be a context diagram extension failure either. I hope @jamilraichouni could share the stack trace with more details.

**Comment by jamilraichouni** [comment]
Try the following at DB:

```python
model = MelodyModel(
    path="git+https://git.tech.rz.db.de/dbb_sea/redbox.git",
    revision="main",
    entrypoint="RedBox.aird",
    diagram_cache=
    (
        "http://<USER>:<PASSWORD>"
        "@internal-ac7fe49fbe783451ba3a1af3c6784b1f-1905475508.eu-central-1.elb.amazonaws.com"
        "/redbox/main/diagram"
    )
)
model.la.all_functions[0].context_diagram
```

I get

```python
HTTPError: 500 Server Error: Internal Server Error for url:
http://<USER>:<PASSWORD>@internal-ac7fe49fbe783451ba3a1af3c6784b1f-1905475508.eu-central-1.elb.amazonaws.com/redbox/main/diagram/2ada1b67-5a6a-438d-b198-274e19b12fd5_context.svg
```

So maybe the Diagram server shall return something else than 500

**Comment by jamilraichouni** [comment]
Modified the return code for the Diagram server from 500 to 404.
That makes more sense here and seems to be handled in capellambse.

**Comment by Wuestengecko** [comment]
Can this issue be closed, or is there something else that needs to be done? If so, what is needed / expected in order to close this issue?

**Comment by jamilraichouni** [comment]
New return code leads to expected behaviour
