### ISSUE TITLE
Publication for Capella

### ISSUE THREAD

**Issue by tkSDISW** [DSD-DBS/py-capellambse#465]
I am using a model that is using the OBEO product, Publication for Capella. This model introduces a new file extension for a model, cal .traceability.  In this case the model in CR_Ventilator.

I am now getting an error.

TypeError: Model file CR_Ventilator.traceability has an unsupported extension: .traceability

Is there a way to bypass or ignore this error.

**Comment by Wuestengecko** [comment]
Hi!
This was meant to be a safety check against loading files that potentially don't contain XML, which would crash the entire thing with an extremely unhelpful error. Since we don't currently have access to Publication for Capella internally, I also can't verify what's actually in those `.traceability` files.

For the time being, you might get away with disabling this check, by removing the line that says `_verify_extension(filename)` in `ModelFile.__init__` (around line 219 of `capellambse/loader/core.py`). However, if that crashes, we'll need a slightly better fix.

For the next release, I'll look at how to improve dealing with extra files that we can't handle properly.

**Comment by tkSDISW** [comment]
I made the change by commenting out the code and resulted in following stack trace. 

 `KeyError                                  Traceback (most recent call last)
File Cell [5]:9
      5 resources = {
      6     "CR_Ventilator_Sim": "CR_Ventilator_Sim/CR_Ventilator_Sim",
      7 }
      8 path_to_model = "../CR_Ventilator.aird"
----> 9 model = capellambse.MelodyModel(path_to_model, resources=resources)

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/model/_model.py:261, in MelodyModel.__init__(self, path, diagram_cache, fallback_render_aird, **kwargs)
    137 """Load a project.
    138 
    139 For complete information on which exact ``kwargs`` are
   (...)
    257     A simple ``http(s)://`` file handler.
    258 """
    259 capellambse.load_model_extensions()
--> 261 self._loader = loader.MelodyLoader(path, **kwargs)
    262 self._fallback_render_aird = fallback_render_aird
    264 if diagram_cache:

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/loader/core.py:490, in MelodyLoader.__init__(self, path, entrypoint, resources, ignore_duplicate_uuids_and_void_all_warranties, **kwargs)
    487         self.resources[resname] = reshdl
    489 self.trees: dict[pathlib.PurePosixPath, ModelFile] = {}
--> 490 self.__load_referenced_files(
    491     pathlib.PurePosixPath("\0", self.entrypoint)
    492 )
    494 self.check_duplicate_uuids()

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/loader/core.py:538, in MelodyLoader.__load_referenced_files(self, resource_path)
    534 for ref in _find_refs(frag.root):
    535     ref_name = helpers.normalize_pure_path(
    536         _unquote_ref(ref), base=resource_path.parent
    537     )
--> 538     self.__load_referenced_files(ref_name)

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/loader/core.py:530, in MelodyLoader.__load_referenced_files(self, resource_path)
    528 handler = self.resources[resource_path.parts[0]]
    529 filename = pathlib.PurePosixPath(*resource_path.parts[1:])
--> 530 frag = ModelFile(
    531     filename, handler, ignore_uuid_dups=self.__ignore_uuid_dups
    532 )
    533 self.trees[resource_path] = frag
    534 for ref in _find_refs(frag.root):

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/loader/core.py:228, in ModelFile.__init__(self, filename, handler, ignore_uuid_dups)
    223     tree = etree.parse(
    224         f, etree.XMLParser(remove_blank_text=True, huge_tree=True)
    225     )
    227 self.root = tree.getroot()
--> 228 self.idcache_rebuild()

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/loader/core.py:296, in ModelFile.idcache_rebuild(self)
    294 self.__idcache = {}
    295 self.__hrefsources = {}
--> 296 self.idcache_index(self.root)
    297 LOGGER.debug("Cached %d element IDs", len(self.__idcache))

File /home/simcenter/studio/CR_Ventilator_Sim/CR_Ventilator_Sim/Notebooks/py-capellambse/capellambse/loader/core.py:242, in ModelFile.idcache_index(self, subtree)
    240 def idcache_index(self, subtree: etree._Element) -> None:
    241     """Index the IDs of ``subtree``."""
--> 242     idtypes = IDTYPES_PER_FILETYPE[self.filename.suffix]
    243     for elm in subtree.iter():
    244         xtype = helpers.xtype_of(elm)

KeyError: '.traceability'`

**Comment by Wuestengecko** [comment]
I've made some changes to the loading process, so it ignores these traceability files entirely (we wouldn't properly handle anything in them anyways). Can you please try out PR 470? You can install it by running:

    pip install git+https://github.com/DSD-DBS/py-capellambse.git@ignore-unknown-files

(Return to the latest release with `pip install -U capellambse` )

**Comment by tkSDISW** [comment]
That worked.  Thank you for the quick response. 
I will pass on these issues to the developer of addon. 
They may be interested is contributing to your incredibly useful set of modules.
