### ISSUE TITLE
Attributes for "realizing" and "realized" are missing for capellacommon:State

### ISSUE THREAD

**Issue by malnemark** [DSD-DBS/py-capellambse#56]
In Capella a state can be realized by another state (of a higher level). We are missing ability to check that realization attribute  in the current API.

**Comment by vik378** [comment]
This is how Capella meta-model looks like around states:

![image](https://user-images.githubusercontent.com/8280844/150341764-df7d7f72-c5ad-44e7-be27-35522b1331eb.png)
