### ISSUE TITLE
SAB diagram - multiple rendering issues

### ISSUE THREAD

**Issue by vik378** [DSD-DBS/py-capellambse#64]
SAB diagram rendered by our default engine has missing features and incorrect placement issues:

* Function ports are not shown
* ComponentExchange edges go into and above the Component Ports
* port allocation links go above ports
* Component Port direction is identified erroneously 

![image](https://user-images.githubusercontent.com/8280844/154484855-6a7028a7-4b7b-435e-9cbf-ec5f532621ab.png)

**Comment by Wuestengecko** [comment]
Should be fixed with merge of #72. (If not, please reopen.)
