### ISSUE TITLE
API for accessing auxiliary files

### ISSUE THREAD

**Issue by Wuestengecko** [DSD-DBS/py-capellambse#65]
In addition to the model itself, there can also exist auxiliary files next to it. These files are defined by users of the model. This will be especially useful in conjunction with the GitFileHandler or similar, where such files would be downloaded automatically and transparently to the user.

In order to implement this functionality, we first need to define an appropriate API:

1. How files can be accessed from a `MelodyModel` instance.
2. How the `MelodyLoader` provides access to the underlying file handler.
3. How to access directories and enumerate files in them.

The first two points can be solved in a very simple and effective manner by exposing the actual FileHandler object. This allows the FileHandler to implement any arbitrary API without having to worry about name collisions with attributes of the model object.

For the last point we can implement a `PathLike` API. This is both user friendly and allows code that works with `pathlib.Path` objects to also transparently handle files in the file handler.

**Comment by henrik997** [comment]
This issue is obsolete by using libaries properly, i.e. instantiation a RPL from REC, right?

**Comment by Wuestengecko** [comment]
This is now possible by using the FileHandler objects from the `model.resources` dictionary.
